Update patch set 4
Patch Set 4:

Flake8 Violations: 58
First 13 shown
---
 ./sfc/tests/functest/run_sfc_tests.py:18:1: F401 'functest.utils.openstack_utils as os_utils' imported but unused
 ./sfc/tests/functest/run_sfc_tests.py:34:55: E231 missing whitespace after ','
 ./sfc/tests/functest/run_sfc_tests.py:41:80: E501 line too long (92 > 79 characters)
 ./sfc/tests/functest/run_sfc_tests.py:84:5: E303 too many blank lines (2)
 ./sfc/tests/functest/run_sfc_tests.py:92:53: W291 trailing whitespace
 ./sfc/tests/functest/run_sfc_tests.py:102:1: W293 blank line contains whitespace
 ./sfc/tests/functest/run_sfc_tests.py:109:9: F841 local variable 'a_controller' is assigned to but never used
 ./sfc/lib/config.py:31:5: E301 expected 1 blank line, found 0
 ./sfc/lib/config.py:35:92: E202 whitespace before ')'
 ./sfc/lib/utils.py:18:1: F811 redefinition of unused 're' from line 12
 ./sfc/lib/utils.py:571:29: E201 whitespace after '('
 ./sfc/lib/utils.py:580:11: E128 continuation line under-indented for visual indent
 ./sfc/lib/utils.py:668:1: E302 expected 2 blank lines, found 1

Patch-set: 4