Update patch set 1
Patch Set 1:

Flake8 Violations: 1
First 1 shown
---
 ./tests/functest/odl-sfc/utils.py:7:1: F811 redefinition of unused 'ft_utils' from line 5

Patch-set: 1
Label: Verified=-1