Update patch set 4
Patch Set 4:

It seems that the location of the setup.py makes the package be functest or am I missing something? 
I ran python setup.py install in a venv and I get:

(venv) 
~/Code/sfc/tests on ? master ? 10:10:56
$ python -c "from sfc import functest"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sfc
(venv) 
~/Code/sfc/tests on ? master ? 10:12:06
$ python -c "import functest"            
(venv) 

which seems like it installs it as `functest`

Patch-set: 4
Label: Verified=0