Bug fix: pass variables in the class constructor
The Testcase class requires parameters in the constructor. We should pass
them or otherwise we get an error:

https://github.com/opnfv/functest-xtesting/blob/master/xtesting/core/testcase.py#L48

ERROR:

TypeError: "__init__() got an unexpected keyword argument 'project_name'"

Change-Id: I6f4b62b7ff201bf6878004e3fb452778c6b55f0e
Signed-off-by: Manuel Buil <mbuil@suse.com>